###PRODUCTS CREATE
POST http://localhost:3000/products.json
Content-Type: application/json

{
  "name": "Harry Potter",
  "price": 35,
  "image_url": "image_example.com",
  "description": "Best book series of all time."

}

###PRODUCTS SHOW
GET http://localhost:3000/products/4.json

###PRODUCTS INDEX
GET http://localhost:3000/products.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDc5NzIwNzZ9.Adb41h-Bs3hvh9kCImYZn2nMeaCFRuoiC8sEoaBfVmQ

###PRODUCTS UPDATE
PATCH http://localhost:3000/products/3.json
Content-Type: application/json

{
  "name": "Shakespeare's works",
  "price": 15,
  "description": "Most beautiful plays ever written."

}

###PRODUCTS DESTROY
DELETE http://localhost:3000/products/5

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Aaron",
  "email": "Aaron@example.com",
  "password": "thisisapassword!",
  "password_confirmation": "thisisapassword!"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "Aaron@example.com",
  "password": "thisisapassword!"
}

###ORDERS CREATE
POST http://localhost:3000/orders
Content-Type: application/json

{
    "user_id": 2,
    "product_id": 2,
    "quantity": 2,
    "subtotal": 24.1,
    "tax": 2.16,
    "total": 26.16
}

###ORDERS SHOW
GET http://localhost:3000/orders/2


