###PRODUCTS CREATE
POST http://localhost:3000/products.json
Content-Type: application/json

{
  "name": "Harry Potter",
  "price": 35,
  "image_url": "image_example.com",
  "description": "Best book series of all time."

}

###PRODUCTS SHOW
GET http://localhost:3000/products/4.json

###PRODUCTS INDEX
GET http://localhost:3000/products.json

###PRODUCTS UPDATE
PATCH http://localhost:3000/products/3.json
Content-Type: application/json

{
  "name": "Shakespeare's works",
  "price": 15,
  "description": "Most beautiful plays ever written."

}

###PRODUCTS DESTROY
DELETE http://localhost:3000/products/5
